import { Dimensions, StyleSheet, Platform } from "react-native";
import { RFPercentage, RFValue } from "react-native-responsive-fontsize";
import * as Colors from "../../common/colors";
import * as Fonts from "../../common/Fonts";

const windowWidth = Dimensions.get("screen").width;
const windowHeight = Dimensions.get("screen").height;

const { width, height } = Dimensions.get("screen");

export const InnerStyle = StyleSheet.create({
  container: {
    // flex:1,
  },
  HeaderImage: {
    flex: 1,
    backgroundColor: Colors.White,
    width: windowWidth,
    height: windowHeight / 3,
  },
  VideoStyle: {
    flex: 1,
    width: windowWidth,
    height: windowHeight / 3,
  },
  HeaderViewStyle: {
    marginHorizontal: RFValue(14),
    marginTop: RFPercentage(7),
  },
  SecoundHeaderTitleStyle: {
    // marginHorizontal: RFValue(14),
    //     backgroundColor:'red'
  },
  DrawerIconStyle: {
    height: RFPercentage(3.5),
    width: RFPercentage(3.5),
  },
  TextViewStyle: {
    paddingTop: RFPercentage(2),
  },
  HeaderTextStyle: {
    color: Colors.White,
    fontFamily: Fonts.Bold,
    fontSize: RFValue(18),
  },
  HeaderChildTextStyle: {
    color: Colors.White,
    paddingVertical: RFValue(5),
    fontFamily: Fonts.Medium,
    fontSize: RFValue(14),
  },
  SearchViewStyle: {
    // paddingVertical:RFPercentage(0.1),
    alignSelf: "center",
    width: windowWidth / 1.1,
    marginVertical: RFPercentage(2),
    flexDirection: "row",
    backgroundColor: Colors.SearchBar,
    borderRadius: RFPercentage(1.5),
    // borderWidth:2,
    // borderColor : 'rgba(255, 255, 255, 0.63)',
    // shadowColor: "#000",
    // shadowOffset: { width: 0, height: 3 },
    // shadowRadius: 2,
    // shadowOpacity: 0.2,
    // elevation: 3,
  },
  SearchIconStyle: {
    tintColor: Colors.Black,
    alignSelf: "center",
    height: RFPercentage(2),
    width: RFPercentage(2),
    paddingHorizontal: RFPercentage(3.2),
  },
  TextInputInnerStyle: {
    paddingVertical:
      Platform.OS === "ios" ? RFPercentage(1.5) : RFPercentage(1),
    width: windowWidth / 1.25,
    fontWeight: "bold",
    // backgroundColor:"blue",
    color: Colors.Black,
    fontSize: RFValue(12),
    fontFamily: Fonts.Medium,
  },
  SecoundMainviewStyle: {
    flex: 2,
    backgroundColor: Colors.DarkBlue,
    paddingHorizontal: RFValue(14),
  },
  HeaderSecoundStyle: {
    // marginTop: '4%',
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    // backgroundColor:"blue",
    // marginBottom: RFValue(5),
    // paddingVertical:RFPercentage(0.5),
  },
  ProfileInfoStyle: {
    // justifyContent:'space-between',
    // paddingVertical:RFPercentage(1),
    // marginVertical:RFPercentage(1),
    // backgroundColor:'red',
  },
  StaticImageStyle: {
    height: RFPercentage(6),
    width: RFPercentage(6),
  },
  WelcomeTextStyle: {
    // paddingVertical:RFPercentage(1),
    color: Colors.White,
    fontSize: RFValue(17),
    fontFamily: Fonts.SemiBold,
  },
  DateInfoTextStyle: {
    color: Colors.White,
    fontFamily: Fonts.Regular,
    fontSize: RFValue(12),
  },
  SectionView: {
    flexDirection: "row",
    flexWrap: "wrap",
    width: windowWidth,
    justifyContent: "center",
    alignSelf: "center",
    marginVertical: RFPercentage(2),
  },
  ExploreTopicStyle: {
    flexDirection: "row",
    flexWrap: "wrap",
    width: windowWidth,
    height: "45%",
    justifyContent: "center",
    alignSelf: "center",
    // maxWidth:'20%',
  },
  InnerMainViewStyle: {
    // padding: RFPercentage(1),
    // flex:1,
    // width:windowWidth/2.1,
    // paddingVertical:RFPercentage(1),
  },
  BottonViewStyle: {
    // borderRadius:RFPercentage(5),
  },
  ImageContainerStyle: {
    height: windowWidth / 2.31,
    width: windowWidth / 2.31,
    justifyContent: "center",
    overflow: "hidden",
    borderRadius: RFValue(15),
    justifyContent: "space-between",
    alignItems: "center",

    // height: RFPercentage(22),
    // width: RFPercentage(22),
  },
  InnerTextStyle: {
    color: Colors.White,
    fontFamily: Fonts.SemiBold,
    fontSize: RFValue(12),
    paddingTop: RFPercentage(2),
  },
  InnerIconStyle: {
    height: RFPercentage(5),
    width: RFPercentage(5),
  },
  SessionTextStyle: {
    color: Colors.White,
    fontFamily: Fonts.SemiBold,
    fontSize: RFValue(12),
    paddingBottom: RFPercentage(2),
  },
  // Relatation Screen Style
  RelatationHeaderImageStyle: {
    flex: 1,
    height: RFPercentage(20),
    width: windowWidth,
  },
  mainScrollViewStyle: {
    // justifyContent: "space-evenly",
    // backgroundColor: Colors.LigthGray,
    marginVertical: RFPercentage(1),
    flexDirection: "row",
    marginHorizontal: RFValue(14),
    borderRadius: RFPercentage(2),
    // backgroundColor:"red",
  },
  MainChildViewStyle: {
    // width: windowWidth / 1.5,
    // backgroundColor:'grey',
    // borderRadius: RFPercentage(2),
    // paddingVertical: RFPercentage(1),
    flexDirection: "row",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: RFPercentage(1),
    // backgroundColor:"blue",
  },
  FirstImageStyle: {
    height: RFPercentage(10),
    width: RFPercentage(16),
    // marginVertical: RFValue(4),
    // paddingHorizontal: RFPercentage(1),
    flexDirection: "column-reverse",
    marginRight: RFPercentage(1),
  },
  TextSectionStyle: {
    justifyContent: "space-around",
    // alignSelf: "center",
    width: windowWidth / 1.7,
    // backgroundColor:"blue",
  },
  get HeaderTextSectionStyle() {
    return this._HeaderTextSectionStyle;
  },
  set HeaderTextSectionStyle(value) {
    this._HeaderTextSectionStyle = value;
  },
  FistTextStyle: {
    color: Colors.White,
    fontSize: RFValue(15),
    fontFamily: Fonts.Bold,
  },
  SecoundTextStyle: {
    color: Colors.White,
    fontSize: RFValue(10),
  },
  SecoundTextTimeStyle: {
    color: Colors.LigthGray,
    fontSize: RFValue(8),
  },
  PlayButtonViewStyle: {
    justifyContent: "center",
    // left: RFPercentage(10),
  },
  PlayButtonStyle: {
    height: RFPercentage(5),
    width: RFPercentage(5),
  },
  // Notificatation Screen Design
  HeaderMainStyle: {
    marginTop: RFPercentage(7),
    paddingHorizontal: RFValue(14),
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  HeaderTitle: {
    justifyContent: "center",
    fontFamily: Fonts.Bold,
    color: Colors.White,
    fontSize: RFValue(14),
    // lineHeight:17,
  },
  BlankSpace: {
    height: RFPercentage(3.5),
    width: RFPercentage(3.5),
  },
  DataMainView: {
    paddingHorizontal: RFPercentage(2),
    marginVertical: RFPercentage(4),
  },
  DataRenderMainView: {
    flexDirection: "row",
    backgroundColor: Colors.DarkBlue,
    marginVertical: RFPercentage(1),
    paddingVertical: RFPercentage(2),
    paddingHorizontal: RFPercentage(2),
    borderRadius: RFPercentage(2),
  },
  NotifiInnerImage: {
    // marginHorizontal: RFPercentage(1),
    height: RFPercentage(5),
    width: RFPercentage(5),
    backgroundColor: Colors.LigthGray,
    borderRadius: RFPercentage(5),
  },
  NotifyTitleStyle: {
    // paddingVertical:RFPercentage(1),
    color: Colors.White,
    fontFamily: Fonts.SemiBold,
  },
  NotifyDiscStyle: {
    color: Colors.White,
    fontFamily: Fonts.Regular,
  },
  //Music Page Style
  HeaderTitleTextViewStyle: {
    paddingHorizontal: RFValue(16),
    marginVertical: RFPercentage(5),
  },
  HeaderDiscTextStyle: {
    color: Colors.White,
    fontFamily: Fonts.SemiBold,
    fontSize: RFValue(13),
  },
  ProfileSecoundMainViewStyle: {
    backgroundColor: Colors.DarkBlue,
    marginTop: RFPercentage(4),
    paddingHorizontal: RFValue(14),
    flex: 1,
    borderTopRightRadius: RFPercentage(5),
    borderTopLeftRadius: RFPercentage(5),
  },
  ProfileInnerStyle: {
    borderRadius: RFPercentage(2),
    marginTop: RFPercentage(6),
    flexDirection: "row",
    alignItems: "center",
  },
  ProfileIMG: {
    height: RFPercentage(10),
    width: RFPercentage(10),
    backgroundColor: Colors.White,
    borderRadius: RFPercentage(5),
  },
  BasicInfoStyle: {
    paddingLeft: RFPercentage(1),
    height: RFPercentage(7),
    justifyContent: "space-between",
    width: windowWidth / 1.3,
  },
  ProfileNameTextStyle: {
    color: Colors.White,
    fontFamily: Fonts.Bold,
    fontSize: RFValue(12),
  },
  ProfileSectionMainViewStyle: {
    marginTop: RFPercentage(5),
  },
  ProfileSectionStyle: {
    // marginVertical: RFPercentage(3),
    flexDirection: "row",
    justifyContent: "space-between",
  },
  ProfileTextStyle: {
    color: Colors.White,
    fontFamily: Fonts.Bold,
    fontSize: RFPercentage(2),
  },
  RigthArrowStyle: {
    height: RFPercentage(2),
    width: RFPercentage(2),
    alignSelf: "center",
  },
  horozontalLine: {
    marginVertical: RFPercentage(3),
    height: 1,
    backgroundColor: Colors.White,
  },
  // Edit Profile Style
  SecoundInnerViewStyle: {
    justifyContent: "center",
    alignSelf: "center",
    marginTop: RFPercentage(5),
  },
  ChangeImageTextStyle: {
    color: Colors.White,
    textAlign: "center",
    fontFamily: Fonts.SemiBold,
    paddingVertical: RFPercentage(1),
  },
  staticTextStyle: {
    color: Colors.White,
    fontFamily: Fonts.SemiBold,
  },
  TextInputViewStyle: {
    marginVertical: RFPercentage(2),
  },
  TextinputStyle: {
    paddingTop: RFPercentage(1),
    color: Colors.Black,
  },
  BtnTouchStyle: {
    marginVertical: RFPercentage(4),
    borderRadius: RFPercentage(5),
    backgroundColor: Colors.Green,
    alignSelf: "center",
  },
  BtnInnerStyle: {
    color: Colors.White,
    paddingHorizontal: RFPercentage(5),
    paddingVertical: RFPercentage(1.5),
    fontFamily: Fonts.Bold,
  },
  // Purchase Screen Design
  SecoungMainViewStyle: {
    marginVertical: RFPercentage(5),
  },

  // Meditation Screen

  Medi_BackGroundImage: {
    display: "flex",
    height: height / 2.2,
    width: width,
    // paddingTop: Platform.OS === 'android' ? RFPercentage(4) : null,
  },
  Medi_headerContainer: {
    padding: RFValue(14),
    paddingTop: RFPercentage(7),
  },
  Medi_headerText: {
    color: Colors.White,
    fontSize: RFValue(35),
    fontFamily: Fonts.Bold,
  },
  Medi_headerSubText: {
    color: Colors.White,
    fontSize: RFValue(25),
    fontFamily: Fonts.Regular,
    marginTop: RFValue(10),
  },
  SessionCard: {
    display: "flex",
    height: height,
    backgroundColor: Colors.DarkBlue,
    alignItems: "center",
    marginTop: -RFPercentage(8),
    borderRadius: RFValue(50),
    paddingVertical: RFValue(25),
  },
  SessionTitle: {
    color: Colors.White,
    fontSize: RFValue(20),
    fontFamily: Fonts.Regular,
  },
  SessionTime: {
    color: Colors.White,
    fontSize: RFValue(45),
    fontFamily: Fonts.Regular,
  },
  linearButton: {
    borderRadius: RFPercentage(50),
  },
  Forward: {
    height: RFValue(70),
    width: RFValue(70),
    alignSelf: "center",
    marginLeft: RFValue(8),
  },
  Reverse: {
    height: RFValue(70),
    width: RFValue(70),
    alignSelf: "center",
    marginRight: RFValue(8),
  },

  Play_Pause: {
    height: RFValue(90),
    width: RFValue(90),
    tintColor: Colors.White,
  },
  BackButton: {
    color: Colors.White,
    fontSize: RFValue(15),
    fontFamily: Fonts.SemiBold,
  },
  Medi_Back: {
    borderColor: Colors.White,
    borderWidth: 1,
    borderRadius: RFValue(23),
    width: RFValue(175),
    padding: RFValue(4),
    alignItems: "center",
    marginTop: RFValue(30),
  },
  For_RevContainer: {
    flex: 1,
    justifyContent: "center",
  },
  PlayerContainer: {
    borderColor: "red",
    flexDirection: "row",
    padding: RFValue(20),
    marginTop: RFValue(18),
  },
  left_arrow: {
    height: RFValue(25),
    width: RFValue(25),
    marginStart: RFPercentage(2),
    marginBottom: RFPercentage(-20),
  },
  DrawerIconStyle2: {
    // marginTop: RFPercentage(7.3),
    // height: RFPercentage(3),
    // width: RFPercentage(3),
    // paddingHorizontal:RFValue(14),
  },
  // Main Lotus Screen Design
  LotusSecoundSectionStyle: {
    width: windowWidth / 2.2,
    marginVertical: RFPercentage(2),
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  SectionInnerStyle: {
    backgroundColor: Colors.BoxColor,
    borderRadius: RFValue(10),
    height: windowHeight / 3.5,
    width: windowWidth / 2.5,
    justifyContent: "space-evenly",
  },
  ImageTextViewStyle: {
    bottom: RFValue(15),
    alignItems: "center",
  },
  LotusScreenImageStyle: {
    height: RFPercentage(12),
    width: RFPercentage(12),
    borderRadius: RFPercentage(12),
  },
  CommonTextStyle: {
    textAlign: "left",
    color: Colors.White,
    fontFamily: Fonts.Regular,
    fontSize: RFValue(10),
  },
  SubViewStyle: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  SubInnerViewStyle: {
    height: RFPercentage(5.5),
    width: RFPercentage(5.5),
    backgroundColor: Colors.DarkBlue,
    justifyContent: "space-around",
    borderRadius: RFValue(5),
  },
  StaticImageStyle1: {
    height: RFPercentage(2.2),
    width: RFPercentage(2.2),
    alignSelf: "center",
  },
  StaticDollarImageStyle: {
    height: RFPercentage(2.8),
    width: RFPercentage(2.8),
    alignSelf: "center",
  },
  CommonDinamicTextStyle: {
    fontFamily: Fonts.Bold,
    fontSize: RFValue(9),
    color: Colors.White,
    textAlign: "center",
  },
  //-----------------------------------------------------------------//
  //-------RelationScreen(new) start here----------------------------//
  RelationShipScreen_Header: {
    flex: 1,
    // backgroundColor: Colors.DarkBlue,
  },
  RelatatioShip_Background: {
    backgroundColor: Colors.DarkBlue,
    height: windowHeight / 3,
    width: windowWidth,
  },
  VideoCard_MainContainer: {
    // backgroundColor: Colors.DarkBlue,
    // padding: RFValue(14),
    paddingHorizontal: RFValue(14),
    flex: 1,
  },
  VideoCard_SubContainer: {
    display: "flex",
    marginHorizontal: RFPercentage(0.1),
    // marginTop:RFPercentage(1),
    height: "85%",
    justifyContent: "center",
    // flexDirection: "row",
    borderRadius: RFPercentage(1.5),
    backgroundColor: Colors.White,
    marginBottom: RFValue(5),
    borderWidth: 2,
    borderColor: "rgb(230,227,224)",
    // shadowColor: "#000",
    // shadowOffset: { width: 0, height: 0 },
    // shadowRadius: 2,
    // shadowOpacity: 0.2,
    // elevation: 5,
  },
  //VC = VideoCard ,
  VC_SubChild1: {
    // flex: 1.1,
    display: "flex",
    // justifyContent: "center",
    // backgroundColor:'blue',
    justifyContent: "center",
  },
  VC_SubChild2: {
    flex: 2.4,
    padding: RFValue(5),
  },
  //SC1=SubChild 1
  VC_SC1_child1: {
    flex: 1.4,
    display: "flex",
    justifyContent: "center",
    flexDirection: "row",
  },
  VC_SC1_child2: {
    flex: 0.4,
    display: "flex",
    flexDirection: "row",
  },
  VC_PlayButtonContainer: {
    // flex: 1,
    backgroundColor: "red",
    // display: "flex",
    // paddingTop: RFValue(8),
  },
  VC_MainText: {
    flex: 2,
    display: "flex",
    paddingTop: RFValue(18),
  },
  VideoType: {
    flex: 0.8,
    display: "flex",
    paddingTop: RFValue(8),
  },
  VideoMinutes: {
    flex: 0.6,
    display: "flex",
    marginBottom: RFValue(8),
  },

  VC_TitileText: {
    color: "white",
    fontSize: RFValue(13),
    fontFamily: Fonts.SemiBold,
  },
  VC_DescriptionText: {
    color: "white",
    fontSize: RFValue(12),
    fontFamily: Fonts.Regular,
  },
  VC_TypeText: {
    color: "white",
    fontSize: RFValue(10),
    fontFamily: Fonts.SemiBold,
  },
  VC_MinuteText: {
    color: "white",
    fontSize: RFValue(12),
    fontFamily: Fonts.SemiBold,
  },
  VC_Image: {
    height: RFPercentage(13),
    width: RFPercentage(13),
    alignSelf: "center",
    borderRadius: RFPercentage(1.5),
  },
  VC_PlayImage: {
    height: RFPercentage(2.5),
    width: RFPercentage(2.5),
  },
  RelationvideoImage_lock: {
    height: RFPercentage(2.5),
    width: RFPercentage(2.5),
    borderRadius: RFValue(10),
  },
  HoursText: {
    color: Colors.Grey,
    marginTop: RFValue(2),
    fontSize: RFValue(11),
    fontFamily: Fonts.SemiBold,
  },
  //-------RelationScreen(new) ends here-----------------------------//
  //------------------------------------------//

  //-----------------------------------------//
  //Next Video List/Modal- -----------------------------------------//
  //-----------------------------------------//

  MC_MainContainer: {
    height: windowHeight,
    justifyContent: "center",
    backgroundColor: Colors.White,
  },
  VideoPlayerContainer: {
    // flex: 1,
    // alignSelf: "center",
    // justifyContent: "center",
    // paddingVertical:RFPercentage(1),
  },
  NextvideoContainer: {
    paddingVertical: RFPercentage(1),
    flexDirection: "row",
    alignItems: "center",
  },
  NvC_Text: {
    paddingHorizontal: RFValue(14),
    fontFamily: Fonts.Bold,
    fontSize: RFValue(15),
    color: "#000000",
  },
  NextImg: {
    height: RFPercentage(3),
    width: RFPercentage(3),
    tintColor: Colors.LigthGray,
  },
  NextvideoList: {
    marginTop: RFValue(8),
    marginBottom: RFValue(15),
    borderRadius: RFValue(10),
    height: RFPercentage(25),
    justifyContent: "center",
    width: RFPercentage(22),
    alignItems: "center",
  },
  NextvideoDetails: {
    marginTop: RFValue(8),
    marginBottom: RFValue(4),
    borderRadius: RFValue(10),
    height: RFPercentage(25),
    width: windowWidth / 2.2,
    alignItems: "center",
  },
  NextvideoImage: {
    height: RFPercentage(25),
    width: RFPercentage(22),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 15,
    marginBottom: RFValue(2),
  },
  NextvideoDetails2: {
    marginTop: RFValue(8),
    borderWidth: 2,
    marginBottom: RFValue(4),
    borderRadius: RFValue(10),
    height: RFPercentage(25),
    width: RFPercentage(22),
    alignItems: "center",
  },
  NvView: {
    flex: 0.8,
    justifyContent: "center",
    alignItems: "center",
  },
  NVViewL: {
    flex: 0.8,
    justifyContent: "center",
    width: "80%",
  },
  NVPlayLock: {
    width: "85%",
    flex: 0.2,
    marginBottom: RFPercentage(3),
  },
  NPlayLock: {
    borderRadius: RFValue(12),
    backgroundColor: Colors.Purple,
    height: RFPercentage(5.5),
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  NvTview: {
    justifyContent: "center",
  },
  NextVideo: {
    flex: 1,
    padding: RFValue(18),
    paddingTop: 0,
  },
  NvDetails: {
    flexDirection: "row",
    justifyContent: "center",
    alignSelf: "flex-start",
    marginTop: RFValue(10),
  },
  NvPlayView: {
    width: "85%",
    flex: 0.2,
    marginBottom: RFPercentage(3),
  },
  NvPlayBtn: {
    borderRadius: RFValue(12),
    backgroundColor: Colors.Purple,
    height: RFPercentage(5.5),
    justifyContent: "center",
  },
  NextvideoImage2: {
    height: RFPercentage(20),
    width: RFPercentage(20),
    alignSelf: "center",
    borderRadius: 15,
    marginBottom: RFValue(2),
  },
  NextvideoList2: {
    marginBottom: RFValue(15),
    borderRadius: RFValue(10),
    height: RFPercentage(24),
    width: RFPercentage(20),
    marginRight: RFValue(10),
  },
  NvV_Text2: {
    fontFamily: Fonts.Bold,
    fontSize: RFValue(11),
    color: Colors.Black,
    textAlign: "center",
  },
  NextvideoImage_lock: {
    position: "absolute",
    height: RFPercentage(3.5),
    width: RFPercentage(3.5),
    tintColor: "white",
    marginTop: RFPercentage(2.2),
    alignSelf: "center",
    alignItems: "center",
    alignContent: "center",
    justifyContent: "center",
  },
  NextvideoImage_lock2: {
    position: "absolute",
    height: RFPercentage(10),
    width: RFPercentage(10),
    tintColor: Colors.Purple,
    marginTop: RFPercentage(2.2),
  },
  NvV_Text: {
    fontFamily: Fonts.Bold,
    fontSize: RFValue(12),
    color: Colors.Black,
    textAlign: "left",
  },
  NvV_Play: {
    fontFamily: Fonts.Bold,
    fontSize: RFValue(16),
    color: Colors.White,
    alignSelf: "center",
  },
  NvV_Type: {
    fontFamily: Fonts.SemiBold,
    fontSize: RFValue(12),
    color: Colors.Grey,
    alignSelf: "flex-start",
    marginTop: RFValue(5),
    textAlign: "center",
  },
  NvV_Rate: {
    fontFamily: Fonts.SemiBold,
    fontSize: RFValue(12),
    color: Colors.White,
    alignSelf: "center",
    marginTop: RFValue(2),
    marginLeft: RFValue(5),
    textAlign: "center",
  },
  NvV_Clock: {
    fontFamily: Fonts.SemiBold,
    fontSize: RFValue(12),
    color: Colors.White,
    alignSelf: "center",
    marginTop: RFValue(2),
    marginLeft: RFValue(5),
    textAlign: "center",
  },
  // Catogary Common Style .......
  innerBottomButtonViewStyle: {
    flexDirection: "row",
    marginVertical: RFValue(10),
    height: RFPercentage(5.6),
    // backgroundColor:"blue",
  },
  ButtnViewCommonStyle: {
    justifyContent: "center",
    alignItems: "center",
    marginRight: RFValue(10),
    width: RFPercentage(22.5),
    borderRadius: RFValue(30),
    backgroundColor: Colors.DarkBlueish,
    flexDirection: "row",
  },
  ButtnViewCommonStyle2: {
    justifyContent: "center",
    alignItems: "center",
    marginRight: RFValue(10),
    width: RFPercentage(22.5),
    borderRadius: RFValue(30),
    backgroundColor: Colors.Purple,
    flexDirection: "row",
  },
  CommonImageStyle: {
    height: RFPercentage(3),
    width: RFPercentage(3),
    marginHorizontal: RFPercentage(1),
  },
  CommonButtonTextStyle: {
    color: Colors.White,
    fontSize: RFValue(11),
    paddingVertical: RFPercentage(1),
    fontFamily: Fonts.Bold,
  },
  NotificationMainViewStyle: {
    marginHorizontal: RFValue(14),
    backgroundColor: Colors.LightPerpale,
    marginVertical: RFPercentage(1),
    borderRadius: RFPercentage(1.5),
    paddingVertical: RFPercentage(1.5),
  },
  NotificationInnerViewStyle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
  },
  NotificationImageStyle: {
    height: RFPercentage(7),
    width: RFPercentage(7),
    borderRadius: RFPercentage(7),
  },
  NotificationTitleStyle: {
    color: Colors.White,
    fontFamily: Fonts.Bold,
    fontSize: RFPercentage(2),
  },
  NotificationDiscStyle: {
    width: windowWidth / 1.8,
    color: Colors.White,
    fontFamily: Fonts.SemiBold,
    fontSize: RFPercentage(1.7),
  },
  NotificationTimeViewStyle: {
    flexDirection: "row",
    alignSelf: "flex-start",
  },
  NotificationTimeIconStyle: {
    height: RFPercentage(2),
    width: RFPercentage(2),
    tintColor: Colors.White,
    alignSelf: "center",
  },
  NotificationTimeTextStyle: {
    color: Colors.White,
    fontFamily: Fonts.SemiBold,
    fontSize: RFPercentage(1.8),
  },

  T_MainView: {
    backgroundColor: "#03092a",
    flex: 1,
  },
  T_MainContainer: {
    flex: 1,
    marginTop: RFPercentage(7),
    paddingHorizontal: RFValue(10),
    backgroundColor: "#03092a",
  },
  M_Title: {
    color: Colors.White,
    fontFamily: Fonts.Bold,
    fontSize: RFValue(15),
  },
  TQ_Titile: {
    color: Colors.White,
    fontFamily: Fonts.SemiBold,
    fontSize: RFValue(14),
  },
  TV_Titile: {
    color: Colors.White,
    fontFamily: Fonts.Bold,
    fontSize: RFValue(12),
    // marginLeft: RFValue(10),
  },

  T_pagesTexts: {
    color: Colors.White,
    fontFamily: Fonts.SemiBold,
    fontSize: RFValue(11.5),
    alignSelf: "center",
  },

  QuotesText: {
    color: Colors.White,
    fontFamily: Fonts.Bold_Italic,
    fontSize: RFValue(12),
    lineHeight: RFPercentage(3),
  },
  QuotesWriter: {
    color: Colors.White,
    fontFamily: Fonts.Bold_Italic,
    fontSize: RFValue(12),
    alignSelf: "flex-end",
  },
  backIcon: {
    height: RFPercentage(3.5),
    width: RFPercentage(3.5),
    // marginRight: RFValue(8),
  },
  trendIcon: {
    height: RFValue(18),
    width: RFValue(18),
    marginLeft: RFValue(5),
    tintColor: "red",
  },
  trendIcon2: {
    height: RFValue(15),
    width: RFValue(15),
    marginLeft: RFValue(5),
    alignSelf: "center",
    tintColor: "red",
  },
  TrendingQuotes: {
    paddingHorizontal: RFValue(14),
    paddingVertical: RFPercentage(2),
  },
  TrendingQuotes2: {
    padding: RFValue(10),
    marginBottom: RFPercentage(10),
  },
  TrendingVideos: {
    paddingHorizontal: RFValue(5),
    // marginBottom: RFValue(8),
  },
  QuotesCardContainer: {
    borderRadius: RFValue(18),
    height: RFPercentage(30),
    marginTop: RFValue(10),
    width: windowWidth / 1.14,
    marginRight: RFValue(10),
  },
  QuotesCard: {
    padding: RFValue(22),
    paddingBottom: 0,
    height: RFPercentage(30),
    borderRadius: RFValue(10),
    borderTopLeftRadius: RFValue(30),
    borderBottomRightRadius: RFValue(30),
    flexDirection: "column",
    justifyContent: "center",
    width: windowWidth / 1.14,
    marginRight: RFValue(10),
  },
  QuotesView: {
    flex: 0.45,
    borderColor: "white",
    justifyContent: "center",
    alignItems: "baseline",
  },
  QutoesBorder: {
    resizeMode: "stretch",
    width: windowWidth / 1.14,
    height: RFPercentage(30),
    tintColor: Colors.GreyBlue,
  },
  QuotesWriterView: {
    flex: 0.15,
    borderColor: "white",
    justifyContent: "center",
  },
  QShareContainer: {
    flex: 0.2,
    justifyContent: "center",
  },
  QShareView: {
    justifyContent: "center",
    flexDirection: "row",
    alignSelf: "flex-end",
  },
  I_download: {
    // alignSelf: "center",
    height: RFPercentage(4),
    width: RFPercentage(4),
    tintColor: Colors.White,
  },
  ImageCard: {
    borderRadius: RFValue(18),
    alignSelf: "center",
    resizeMode: "contain",
    // borderWidth: 1,
    // padding: RFValue(1),
    // marginTop: RFValue(10),
    // height: RFPercentage(25),
    // borderRadius: RFValue(18),
    // justifyContent: "center",
    // borderColor: Colors.GreyBlue,
    // width: windowWidth / 2.35,
    // marginRight: RFValue(10),
  },
  ImageCard2: {
    borderWidth: 1,
    padding: RFValue(1),
    marginTop: RFValue(10),
    height: RFPercentage(25),
    alignItems: "center",
    // backgroundColor:"red",
    borderColor: Colors.GreyBlue,
    borderRadius: RFValue(10),
  },
  VideoCard: {
    // borderWidth: 1,
    marginTop: RFPercentage(5),
    // width: windowWidth / 2.35,
    // height: RFPercentage(28),
    marginRight: RFValue(10),
    flexDirection: "column",
    // justifyContent: "center",
    // borderColor: Colors.GreyBlue,
  },
  VideoCard1: {
    borderWidth: 1,
    marginTop: RFValue(15),
    width: windowWidth / 2.35,
    height: RFPercentage(28),
    marginRight: RFValue(10),
    borderRadius: RFValue(18),
    borderBottomRightRadius: 0,
    borderTopRightRadius: 0,
    flexDirection: "column",
    justifyContent: "center",
    borderColor: Colors.GreyBlue,
  },
  VideoCard2: {
    borderWidth: 1,
    marginTop: RFValue(15),
    width: windowWidth / 2.35,
    height: RFPercentage(28),
    marginRight: RFValue(10),
    borderRadius: RFValue(18),
    borderTopRadius: 0,
    borderBottomLeftRadius: 0,
    borderTopLeftRadius: 0,
    flexDirection: "column",
    justifyContent: "center",
    borderColor: Colors.GreyBlue,
  },
  downloadContainer: {
    alignItems: "flex-end",
  },
  downloadView: {
    width: RFPercentage(4),
    justifyContent: "center",
    height: RFPercentage(4),
    borderRadius: 50,
    backgroundColor: Colors.LigthBlue,
  },
  PlayContainer: {
    // backgroundColor:"blue",
    // marginTop: RFPercentage(2),
    // justifyContent: "center",
    // position: "absolute",
    alignSelf: "center",
  },
  PlayImg: {
    alignSelf: "center",
    height: RFPercentage(4),
    width: RFPercentage(4),
    tintColor: Colors.White,
  },
  VideoCardImage: {
    height: RFPercentage(30),
    width: RFPercentage(25),
    justifyContent: "space-between",
  },
  VideoContainer: {
    borderRadius: RFValue(18),
    alignSelf: "center",
    resizeMode: "contain",
  },
  VideoDetails: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    borderBottomLeftRadius: RFValue(18),
    borderBottomRightRadius: RFValue(18),
  },
  ImageStyle: {
    height: "100%",
    width: "100%",
    borderRadius: RFValue(10),
  },
  T_pages: {
    marginTop: RFPercentage(2),
    justifyContent: "space-evenly",
    flexDirection: "row",
  },
  T_pageslist: {
    borderWidth: 1,
    backgroundColor: Colors.DarkBlue,
    height: RFPercentage(4),
    width: RFPercentage(10),
    marginRight: RFValue(10),
    borderRadius: RFValue(15),
    resizeMode: "contain",
    borderColor: Colors.GreyBlue,
    justifyContent: "center",
    flexDirection: "row",
  },
  T_pageslist2: {
    borderWidth: 1,
    backgroundColor: Colors.GreyBlue,
    height: RFPercentage(4),
    width: RFPercentage(10),
    marginRight: RFValue(10),
    borderRadius: RFValue(15),
    resizeMode: "contain",
    borderColor: Colors.GreyBlue,
    justifyContent: "center",
    flexDirection: "row",
  },
  Share: {
    borderWidth: 1,
    height: RFPercentage(10),
    width: RFPercentage(10),
    position: "absolute",
    justifyContent: "center",
    alignSelf: "center",
  },
  Share_Img: {
    height: RFPercentage(2.8),
    width: RFPercentage(2.8),
    alignSelf: "flex-end",
    marginEnd: RFPercentage(2),
    tintColor: "white",
  },
});
