require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false
target 'ClarityValley' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  pod 'react-native-voice', :path => '../node_modules/@react-native-voice/voice'

  pod 'react-native-blob-util', :path => '../node_modules/react-native-blob-util'
  
  pod 'react-native-fbsdk-next', :path => '../node_modules/react-native-fbsdk-next'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  
    installer.pod_targets.each do |pod|
      if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
        def pod.build_type;
          # Uncomment the line corresponding to your CocoaPods version
           Pod::BuildType.static_library  #>= 1.9
          # Pod::Target::BuildType.static_library # < 1.9
        end
      end
    end
  end

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'react-native-twilio-video-webrtc', path: '../node_modules/react-native-twilio-video-webrtc'

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"

  pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition"

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"  

  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"


  pod 'Firebase/Core'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'


  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNShare', :path => '../node_modules/react-native-share'



  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

 

  target 'ClarityValleyTests' do
    inherit! :complete

    # # Permission Code add Line 
    # permissions_path = '../node_modules/react-native-permissions/ios'
    # pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone" # Use MicroPhone Permission Require 
    # # end Code 
   
    
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
 

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
